<?php

namespace AppBundle\Repository;

/**
 * MatchEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchEventRepository extends \Doctrine\ORM\EntityRepository
{
}
